### PR TITLE
Finalizando getNationalHolidays & getCarnivalDatesFrom2020To2030

### PR DESCRIPTION
**Pull request by vitucomment**

### CODE REVIEW

**Comment by estartandodevs** [comment]
# Resultado

| Descrição | nota |     |
| --------- | ---- | --- |
| 1-getNationalHolidays deve retornar um erro quando o ano for inválido | 0 | :x: |
| 2-getNationalHolidays should return a promise | 0 | :x: |
| 3-getNationalHolidays should return a promise with resolve for year 2020 | 0 | :x: |
| 4-getNationalHolidays should return a promise with resolve for year 2021 | 0 | :x: |
| 5-getNationalHolidays should return a promise with resolve for year 2022 | 0 | :x: |
| 6-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 7-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 8-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 9-getCarnivalDatesFrom2020To2030 should return a promise | 0 | :x: |
| 10-getCarnivalDatesFrom2020To2030 should return a promise with resolve a array of dates of carnival | 0 | :x: |

## Desempenho

| Item |     |
| ---- | --- |
| Média | Insuficiente |
| Percentual de cumprimento de requisitos | 0.00% |

**Comment by estartandodevs** [comment]
# Resultado

| Descrição | nota |     |
| --------- | ---- | --- |
| 1-getNationalHolidays deve retornar um erro quando o ano for inválido | 0 | :x: |
| 2-getNationalHolidays should return a promise | 0 | :x: |
| 3-getNationalHolidays should return a promise with resolve for year 2020 | 0 | :x: |
| 4-getNationalHolidays should return a promise with resolve for year 2021 | 0 | :x: |
| 5-getNationalHolidays should return a promise with resolve for year 2022 | 0 | :x: |
| 6-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 7-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 8-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 9-getCarnivalDatesFrom2020To2030 should return a promise | 0 | :x: |
| 10-getCarnivalDatesFrom2020To2030 should return a promise with resolve a array of dates of carnival | 0 | :x: |

## Desempenho

| Item |     |
| ---- | --- |
| Média | Insuficiente |
| Percentual de cumprimento de requisitos | 0.00% |

**Comment by estartandodevs** [comment]
# Resultado

| Descrição | nota |     |
| --------- | ---- | --- |
| 1-getNationalHolidays deve retornar um erro quando o ano for inválido | 0 | :x: |
| 2-getNationalHolidays should return a promise | 0 | :x: |
| 3-getNationalHolidays should return a promise with resolve for year 2020 | 0 | :x: |
| 4-getNationalHolidays should return a promise with resolve for year 2021 | 0 | :x: |
| 5-getNationalHolidays should return a promise with resolve for year 2022 | 0 | :x: |
| 6-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 7-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 8-getNationalHolidays should return a promise with resolve for year 2025 | 0 | :x: |
| 9-getCarnivalDatesFrom2020To2030 should return a promise | 0 | :x: |
| 10-getCarnivalDatesFrom2020To2030 should return a promise with resolve a array of dates of carnival | 0 | :x: |

## Desempenho

| Item |     |
| ---- | --- |
| Média | Insuficiente |
| Percentual de cumprimento de requisitos | 0.00% |

**Comment by estartandodevs** [comment]
# Resultado

| Descrição | nota |     |
| --------- | ---- | --- |
| 1-getNationalHolidays deve retornar um erro quando o ano for inválido | 1 | :white_check_mark: |
| 2-getNationalHolidays should return a promise | 1 | :white_check_mark: |
| 3-getNationalHolidays should return a promise with resolve for year 2020 | 1 | :white_check_mark: |
| 4-getNationalHolidays should return a promise with resolve for year 2021 | 1 | :white_check_mark: |
| 5-getNationalHolidays should return a promise with resolve for year 2022 | 1 | :white_check_mark: |
| 6-getNationalHolidays should return a promise with resolve for year 2025 | 1 | :white_check_mark: |
| 7-getNationalHolidays should return a promise with resolve for year 2027 | 1 | :white_check_mark: |
| 8-getNationalHolidays should return a promise with resolve for year 2050 | 1 | :white_check_mark: |
| 9-getCarnivalDatesFrom2020To2030 should return a promise | 1 | :white_check_mark: |
| 10-getCarnivalDatesFrom2020To2030 should return a promise with resolve a array of dates of carnival | 1 | :white_check_mark: |

## Desempenho

| Item |     |
| ---- | --- |
| Média | Suficiente |
| Percentual de cumprimento de requisitos | 100.00% |

**Comment by eufelipe** [comment]
Bem simples e objetivo 👏👏👏

Vou por algumas dicas pra vc refletir:

Linha 7:

```
${BASE_API_NATIONAL_HOLIDAYS}/${year}
```

O BASE_API_NATIONAL_HOLIDAYS já tem uma "/" no final, então vai ficar com duas "//" o axios vai entender que é uma URL e consertar mas em outras libs pode dar problema. 


Linha 9:

```
 resolve(res.data[1].date);
```

Ficou bem objetivo e resolveu numa linha, mas se no futuro a ordem do retorno for modificada, e carnaval não estiver mais na posição 1, dará erro e vc terá que mudar o código.
e a leitura do código ficou um pouco prejudicada, não é erro mas poderia melhorar dessa forma:

```
const holidayDates = res.data
const [holidayCarnival] = holidayDates.filter(holiday => holiday.name === 'Carnaval')
resolve(holidayCarnival.date);

```
Se tiver dúvidas sobre essas implementações me pergunte ;)


Linha 12

```reject(error.message = 'Erro ao calcular feriados.')```

pode usar apenas:

```reject('Erro ao calcular feriados.')```



Linha 18:

```
  arrayDatas = [2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030]
```
Sempre utilize *const* e *let* para não criar variáveis globais e evitar erros.

Essa solução funciona perfeitamente, mas se vc precisasse por 100 anos? rsrs

Outras duas formas de fazer: 

```
const arrayDatas = new Array(11).fill(2020).map((date, index) => date + index)
```
Ou

```
const arrayDatas = Array.from({length: 11}, (_, index) => 2020 + index)
```


=)

**Pull request closed without merging**
